trigger: none

name: RemoveImageBuilderTemplate

variables:
  resourceGroupName: aib
  imageTemplateName: win-srv-2k19

pool: Windows

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Install-Module -name Az.ImageBuilder -Force -Scope CurrentUser'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Remove-AzImageBuilderTemplate -ResourceGroupName $(resourceGroupName) -ImageTemplateName $(imageTemplateName) -NoWait'