trigger: none

name: StartImageBuilderTemplate

variables:
  resourceGroupName: aib
  imageTemplateName: win-srv-2k19

pool: Windows

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'TIMEmSYSTEM'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: 'deployment group create -g $(resourceGroupName) -f main.bicep'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Install-Module -name Az.ImageBuilder -Force -Scope CurrentUser'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Start-AzImageBuilderTemplate -ResourceGroupName $(resourceGroupName) -Name $(imageTemplateName) -NoWait'